[package]
name = "opengl_app"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
resolver = "2"
[dependencies]
winit = "0.25.0"
pixels = "0.6.0"